#!/bin/bash
# Simple shell script to run application in dev mode
python manage.py makemigrations --settings=vasuapp.settings.development
python manage.py migrate --settings=vasuapp.settings.development
python manage.py runserver --settings=vasuapp.settings.development
